export const REACT_SKILLS = [
  // 1. Eliminating Waterfalls (CRITICAL)
  {
    id: "rbp-async-defer-await",
    name: "Defer Await to Branches",
    category: "Eliminating Waterfalls",
    impact: "CRITICAL" as const,
    description: "Move await operations into the branches where they're actually used to avoid blocking code paths that don't need them.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/async-defer-await.md",
  },
  {
    id: "rbp-async-parallel",
    name: "Parallel Async Operations",
    category: "Eliminating Waterfalls",
    impact: "CRITICAL" as const,
    description: "Use Promise.all() for independent async operations to run them in parallel instead of sequentially.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/async-parallel.md",
  },
  {
    id: "rbp-async-dependencies",
    name: "Partial Async Dependencies",
    category: "Eliminating Waterfalls",
    impact: "CRITICAL" as const,
    description: "Use better-all for handling partially dependent async operations to maximize parallelism.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/async-dependencies.md",
  },
  {
    id: "rbp-async-api-routes",
    name: "Early Promise Initiation in API Routes",
    category: "Eliminating Waterfalls",
    impact: "CRITICAL" as const,
    description: "Start promises as early as possible in API routes and await them late to maximize concurrent execution.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/async-api-routes.md",
  },
  {
    id: "rbp-async-suspense-boundaries",
    name: "Suspense Boundaries for Streaming",
    category: "Eliminating Waterfalls",
    impact: "CRITICAL" as const,
    description: "Use Suspense boundaries to stream content progressively and avoid blocking the entire render on slow data fetches.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/async-suspense-boundaries.md",
  },

  // 2. Bundle Size Optimization (CRITICAL)
  {
    id: "rbp-bundle-barrel-imports",
    name: "Avoid Barrel File Imports",
    category: "Bundle Size Optimization",
    impact: "CRITICAL" as const,
    description: "Import directly from source files instead of barrel index files to enable proper tree-shaking and reduce bundle size.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/bundle-barrel-imports.md",
  },
  {
    id: "rbp-bundle-dynamic-imports",
    name: "Dynamic Imports for Heavy Components",
    category: "Bundle Size Optimization",
    impact: "CRITICAL" as const,
    description: "Use next/dynamic for heavy components to split them into separate chunks and load them only when needed.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/bundle-dynamic-imports.md",
  },
  {
    id: "rbp-bundle-defer-third-party",
    name: "Defer Third-Party Scripts",
    category: "Bundle Size Optimization",
    impact: "CRITICAL" as const,
    description: "Load analytics, logging, and other third-party scripts after hydration to avoid blocking initial page load.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/bundle-defer-third-party.md",
  },
  {
    id: "rbp-bundle-conditional",
    name: "Conditional Module Loading",
    category: "Bundle Size Optimization",
    impact: "CRITICAL" as const,
    description: "Load large data or modules only when a feature is activated instead of including them in the initial bundle.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/bundle-conditional.md",
  },
  {
    id: "rbp-bundle-preload",
    name: "Preload on Hover/Focus",
    category: "Bundle Size Optimization",
    impact: "CRITICAL" as const,
    description: "Preload resources on hover or focus events to improve perceived performance without eagerly loading everything.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/bundle-preload.md",
  },

  // 3. Server-Side Performance (HIGH)
  {
    id: "rbp-server-auth-actions",
    name: "Authenticate Server Actions",
    category: "Server-Side Performance",
    impact: "MEDIUM-HIGH" as const,
    description: "Authenticate server actions like API routes — never assume the caller is authorized just because the code runs on the server.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/server-auth-actions.md",
  },
  {
    id: "rbp-server-cache-react",
    name: "React.cache for Request Deduplication",
    category: "Server-Side Performance",
    impact: "MEDIUM-HIGH" as const,
    description: "Use React.cache() to deduplicate identical data fetches within a single server request.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/server-cache-react.md",
  },
  {
    id: "rbp-server-cache-lru",
    name: "LRU Cache for Cross-Request Caching",
    category: "Server-Side Performance",
    impact: "MEDIUM-HIGH" as const,
    description: "Use an LRU cache for data that needs to persist across sequential requests, going beyond what React.cache() provides.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/server-cache-lru.md",
  },
  {
    id: "rbp-server-dedup-props",
    name: "Avoid Duplicate RSC Prop Serialization",
    category: "Server-Side Performance",
    impact: "MEDIUM-HIGH" as const,
    description: "Avoid passing the same data multiple times in React Server Component props to reduce serialization overhead.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/server-dedup-props.md",
  },
  {
    id: "rbp-server-serialization",
    name: "Minimize Client Component Data",
    category: "Server-Side Performance",
    impact: "MEDIUM-HIGH" as const,
    description: "Minimize the amount of data serialized and passed from server to client components to reduce payload size.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/server-serialization.md",
  },
  {
    id: "rbp-server-parallel-fetching",
    name: "Parallel Server Component Fetching",
    category: "Server-Side Performance",
    impact: "MEDIUM-HIGH" as const,
    description: "Restructure server components to parallelize independent data fetches instead of awaiting them sequentially.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/server-parallel-fetching.md",
  },
  {
    id: "rbp-server-after-nonblocking",
    name: "Non-Blocking Post-Response Work",
    category: "Server-Side Performance",
    impact: "MEDIUM-HIGH" as const,
    description: "Use after() for work that doesn't need to complete before the response is sent, like logging or analytics.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/server-after-nonblocking.md",
  },

  // 4. Client-Side Data Fetching (MEDIUM-HIGH)
  {
    id: "rbp-client-swr-dedup",
    name: "SWR Request Deduplication",
    category: "Client-Side Data Fetching",
    impact: "MEDIUM-HIGH" as const,
    description: "Use SWR for client-side data fetching to get automatic request deduplication, caching, and revalidation.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/client-swr-dedup.md",
  },
  {
    id: "rbp-client-event-listeners",
    name: "Deduplicate Global Event Listeners",
    category: "Client-Side Data Fetching",
    impact: "MEDIUM-HIGH" as const,
    description: "Deduplicate global event listeners to avoid registering the same handler multiple times across components.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/client-event-listeners.md",
  },
  {
    id: "rbp-client-passive-event-listeners",
    name: "Passive Scroll Event Listeners",
    category: "Client-Side Data Fetching",
    impact: "MEDIUM-HIGH" as const,
    description: "Use passive event listeners for scroll and touch events to unblock the browser's rendering thread.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/client-passive-event-listeners.md",
  },
  {
    id: "rbp-client-localstorage-schema",
    name: "Version and Minimize localStorage Data",
    category: "Client-Side Data Fetching",
    impact: "MEDIUM-HIGH" as const,
    description: "Version your localStorage schema and store only the minimum necessary data to avoid stale state bugs and read overhead.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/client-localstorage-schema.md",
  },

  // 5. Re-render Optimization (MEDIUM)
  {
    id: "rbp-rerender-defer-reads",
    name: "Defer State Reads to Callbacks",
    category: "Re-render Optimization",
    impact: "MEDIUM" as const,
    description: "Don't subscribe to state values that are only read inside callbacks — defer the read to avoid unnecessary re-renders.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/rerender-defer-reads.md",
  },
  {
    id: "rbp-rerender-memo",
    name: "Memoize Expensive Components",
    category: "Re-render Optimization",
    impact: "MEDIUM" as const,
    description: "Extract expensive rendering work into memoized components to prevent unnecessary recalculation on parent re-renders.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/rerender-memo.md",
  },
  {
    id: "rbp-rerender-memo-with-default-value",
    name: "Hoist Default Non-Primitive Props",
    category: "Re-render Optimization",
    impact: "MEDIUM" as const,
    description: "Hoist default non-primitive props (objects, arrays) outside the component to preserve referential equality and prevent memo from breaking.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/rerender-memo-with-default-value.md",
  },
  {
    id: "rbp-rerender-dependencies",
    name: "Primitive Effect Dependencies",
    category: "Re-render Optimization",
    impact: "MEDIUM" as const,
    description: "Use primitive values as useEffect dependencies instead of objects or arrays to avoid infinite re-render loops.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/rerender-dependencies.md",
  },
  {
    id: "rbp-rerender-derived-state",
    name: "Subscribe to Derived Booleans",
    category: "Re-render Optimization",
    impact: "MEDIUM" as const,
    description: "Subscribe to derived boolean selectors instead of raw values to limit re-renders to meaningful state changes.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/rerender-derived-state.md",
  },
  {
    id: "rbp-rerender-derived-state-no-effect",
    name: "Derive State During Render",
    category: "Re-render Optimization",
    impact: "MEDIUM" as const,
    description: "Compute derived state directly during render instead of syncing it via useEffect to avoid an extra render cycle.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/rerender-derived-state-no-effect.md",
  },
  {
    id: "rbp-rerender-functional-setstate",
    name: "Functional setState for Stable Callbacks",
    category: "Re-render Optimization",
    impact: "MEDIUM" as const,
    description: "Use the functional form of setState to create stable callbacks that don't need the current state as a dependency.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/rerender-functional-setstate.md",
  },
  {
    id: "rbp-rerender-lazy-state-init",
    name: "Lazy State Initialization",
    category: "Re-render Optimization",
    impact: "MEDIUM" as const,
    description: "Pass an initializer function to useState for expensive computations to run them only once instead of on every render.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/rerender-lazy-state-init.md",
  },
  {
    id: "rbp-rerender-simple-expression-in-memo",
    name: "Skip Memo for Simple Primitives",
    category: "Re-render Optimization",
    impact: "MEDIUM" as const,
    description: "Avoid wrapping simple primitive expressions in useMemo — the overhead of memoization exceeds the cost of recomputation.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/rerender-simple-expression-in-memo.md",
  },
  {
    id: "rbp-rerender-move-effect-to-event",
    name: "Move Interaction Logic to Event Handlers",
    category: "Re-render Optimization",
    impact: "MEDIUM" as const,
    description: "Put logic triggered by user interactions in event handlers rather than effects to avoid unnecessary re-render cycles.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/rerender-move-effect-to-event.md",
  },
  {
    id: "rbp-rerender-transitions",
    name: "startTransition for Non-Urgent Updates",
    category: "Re-render Optimization",
    impact: "MEDIUM" as const,
    description: "Use startTransition to mark non-urgent state updates so React can prioritize more critical renders first.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/rerender-transitions.md",
  },
  {
    id: "rbp-rerender-use-ref-transient-values",
    name: "Refs for Transient Frequent Values",
    category: "Re-render Optimization",
    impact: "MEDIUM" as const,
    description: "Use refs instead of state for values that change frequently but don't need to trigger a re-render.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/rerender-use-ref-transient-values.md",
  },

  // 6. Rendering Performance (MEDIUM)
  {
    id: "rbp-rendering-animate-svg-wrapper",
    name: "Animate SVG Wrapper Div",
    category: "Rendering Performance",
    impact: "MEDIUM" as const,
    description: "Animate a div wrapper around SVG elements rather than the SVG element itself for better compositor-thread performance.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/rendering-animate-svg-wrapper.md",
  },
  {
    id: "rbp-rendering-content-visibility",
    name: "content-visibility for Long Lists",
    category: "Rendering Performance",
    impact: "MEDIUM" as const,
    description: "Apply content-visibility: auto to off-screen sections of long lists to skip rendering work for invisible content.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/rendering-content-visibility.md",
  },
  {
    id: "rbp-rendering-hoist-jsx",
    name: "Hoist Static JSX Outside Components",
    category: "Rendering Performance",
    impact: "MEDIUM" as const,
    description: "Extract JSX that never changes into module-level constants to avoid recreating React elements on every render.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/rendering-hoist-jsx.md",
  },
  {
    id: "rbp-rendering-svg-precision",
    name: "Reduce SVG Coordinate Precision",
    category: "Rendering Performance",
    impact: "MEDIUM" as const,
    description: "Reduce the decimal precision of SVG path coordinates to shrink file size without visible quality loss.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/rendering-svg-precision.md",
  },
  {
    id: "rbp-rendering-hydration-no-flicker",
    name: "No-Flicker Hydration with Inline Scripts",
    category: "Rendering Performance",
    impact: "MEDIUM" as const,
    description: "Use inline scripts to read client-only data (like localStorage) before paint to prevent hydration flicker.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/rendering-hydration-no-flicker.md",
  },
  {
    id: "rbp-rendering-hydration-suppress-warning",
    name: "Suppress Expected Hydration Mismatches",
    category: "Rendering Performance",
    impact: "MEDIUM" as const,
    description: "Use suppressHydrationWarning for intentional server/client differences to avoid noisy console warnings.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/rendering-hydration-suppress-warning.md",
  },
  {
    id: "rbp-rendering-activity",
    name: "Activity Component for Show/Hide",
    category: "Rendering Performance",
    impact: "MEDIUM" as const,
    description: "Use the Activity component to show and hide UI without unmounting it, preserving state while avoiding layout thrash.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/rendering-activity.md",
  },
  {
    id: "rbp-rendering-conditional-render",
    name: "Ternary Over && for Conditionals",
    category: "Rendering Performance",
    impact: "MEDIUM" as const,
    description: "Use ternary expressions instead of && for conditional rendering to avoid accidentally rendering 0 or falsy values.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/rendering-conditional-render.md",
  },
  {
    id: "rbp-rendering-usetransition-loading",
    name: "useTransition for Loading State",
    category: "Rendering Performance",
    impact: "MEDIUM" as const,
    description: "Prefer useTransition over manual loading state to get React-managed pending indicators tied to the transition lifecycle.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/rendering-usetransition-loading.md",
  },

  // 7. JavaScript Performance (LOW-MEDIUM)
  {
    id: "rbp-js-batch-dom-css",
    name: "Batch DOM CSS Changes",
    category: "JavaScript Performance",
    impact: "LOW-MEDIUM" as const,
    description: "Group CSS changes via class swaps or cssText assignment to minimize layout reflows from multiple individual property updates.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/js-batch-dom-css.md",
  },
  {
    id: "rbp-js-index-maps",
    name: "Build Map for Repeated Lookups",
    category: "JavaScript Performance",
    impact: "LOW-MEDIUM" as const,
    description: "Build an index Map upfront for O(1) lookups instead of repeatedly scanning arrays with find or filter.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/js-index-maps.md",
  },
  {
    id: "rbp-js-cache-property-access",
    name: "Cache Object Properties in Loops",
    category: "JavaScript Performance",
    impact: "LOW-MEDIUM" as const,
    description: "Cache frequently accessed object properties in local variables inside loops to reduce repeated property lookups.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/js-cache-property-access.md",
  },
  {
    id: "rbp-js-cache-function-results",
    name: "Cache Function Results in Module Map",
    category: "JavaScript Performance",
    impact: "LOW-MEDIUM" as const,
    description: "Cache expensive function results in a module-level Map to avoid recomputing the same output across calls.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/js-cache-function-results.md",
  },
  {
    id: "rbp-js-cache-storage",
    name: "Cache Storage Reads in Memory",
    category: "JavaScript Performance",
    impact: "LOW-MEDIUM" as const,
    description: "Cache localStorage and sessionStorage reads in memory to avoid repeated synchronous storage access on every call.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/js-cache-storage.md",
  },
  {
    id: "rbp-js-combine-iterations",
    name: "Combine Filter/Map into One Loop",
    category: "JavaScript Performance",
    impact: "LOW-MEDIUM" as const,
    description: "Combine multiple chained filter, map, and reduce calls into a single loop to reduce iteration overhead on large arrays.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/js-combine-iterations.md",
  },
  {
    id: "rbp-js-length-check-first",
    name: "Length Check Before Expensive Comparison",
    category: "JavaScript Performance",
    impact: "LOW-MEDIUM" as const,
    description: "Check array or string length as a fast early exit before performing expensive comparison or processing operations.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/js-length-check-first.md",
  },
  {
    id: "rbp-js-early-exit",
    name: "Early Return from Functions",
    category: "JavaScript Performance",
    impact: "LOW-MEDIUM" as const,
    description: "Return early from functions as soon as the result is known to avoid unnecessary computation in subsequent code.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/js-early-exit.md",
  },
  {
    id: "rbp-js-hoist-regexp",
    name: "Hoist RegExp Outside Loops",
    category: "JavaScript Performance",
    impact: "LOW-MEDIUM" as const,
    description: "Create RegExp objects outside of loops to avoid recompiling the same regular expression on every iteration.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/js-hoist-regexp.md",
  },
  {
    id: "rbp-js-min-max-loop",
    name: "Loop for Min/Max Instead of Sort",
    category: "JavaScript Performance",
    impact: "LOW-MEDIUM" as const,
    description: "Use a single loop to find min/max values instead of sorting the array, reducing complexity from O(n log n) to O(n).",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/js-min-max-loop.md",
  },
  {
    id: "rbp-js-set-map-lookups",
    name: "Set/Map for O(1) Lookups",
    category: "JavaScript Performance",
    impact: "LOW-MEDIUM" as const,
    description: "Use Set or Map for membership checks and lookups instead of arrays to get constant-time O(1) performance.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/js-set-map-lookups.md",
  },
  {
    id: "rbp-js-tosorted-immutable",
    name: "toSorted() for Immutable Sorting",
    category: "JavaScript Performance",
    impact: "LOW-MEDIUM" as const,
    description: "Use toSorted() instead of sort() to return a new sorted array without mutating the original, preventing subtle state bugs.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/js-tosorted-immutable.md",
  },

  // 8. Advanced Patterns (LOW)
  {
    id: "rbp-advanced-event-handler-refs",
    name: "Store Event Handlers in Refs",
    category: "Advanced Patterns",
    impact: "LOW" as const,
    description: "Store event handler functions in refs to create stable references that don't cause effects to re-run when the handler changes.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/advanced-event-handler-refs.md",
  },
  {
    id: "rbp-advanced-init-once",
    name: "Initialize App State Once",
    category: "Advanced Patterns",
    impact: "LOW" as const,
    description: "Ensure expensive app-level initialization (e.g. SDK setup, feature flags) runs exactly once per app load, not per render.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/advanced-init-once.md",
  },
  {
    id: "rbp-advanced-use-latest",
    name: "useLatest for Stable Callback Refs",
    category: "Advanced Patterns",
    impact: "LOW" as const,
    description: "Use a useLatest hook to always access the most recent version of a callback without including it in dependency arrays.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/rules/advanced-use-latest.md",
  },
];
