export const REACT_NATIVE_SKILLS = [
  // 1. List Performance (CRITICAL)
  {
    id: "rn-list-performance-virtualize",
    name: "Use FlashList for Large Lists",
    category: "List Performance",
    impact: "CRITICAL" as const,
    description: "Replace FlatList with FlashList for large or heterogeneous lists to get better virtualization, recycling, and rendering throughput.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-native-skills/rules/list-performance-virtualize.md",
  },
  {
    id: "rn-list-performance-item-memo",
    name: "Memoize List Item Components",
    category: "List Performance",
    impact: "CRITICAL" as const,
    description: "Wrap list item components with React.memo to prevent unnecessary re-renders when the parent list updates.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-native-skills/rules/list-performance-item-memo.md",
  },
  {
    id: "rn-list-performance-callbacks",
    name: "Stabilize Callback References",
    category: "List Performance",
    impact: "CRITICAL" as const,
    description: "Use useCallback to stabilize functions passed as props to list items so memoization isn't broken by new function references on every render.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-native-skills/rules/list-performance-callbacks.md",
  },
  {
    id: "rn-list-performance-inline-objects",
    name: "Avoid Inline Style Objects in Lists",
    category: "List Performance",
    impact: "CRITICAL" as const,
    description: "Avoid creating inline style objects inside list item render functions — they create new references each render and break memoization.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-native-skills/rules/list-performance-inline-objects.md",
  },
  {
    id: "rn-list-performance-function-references",
    name: "Extract Functions Outside Render",
    category: "List Performance",
    impact: "CRITICAL" as const,
    description: "Define functions outside the component render scope or stabilize with useCallback to prevent new references causing unnecessary re-renders in lists.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-native-skills/rules/list-performance-function-references.md",
  },
  {
    id: "rn-list-performance-images",
    name: "Optimize Images in Lists",
    category: "List Performance",
    impact: "CRITICAL" as const,
    description: "Use optimized image components and proper sizing inside lists to reduce memory spikes and layout cost during scrolling.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-native-skills/rules/list-performance-images.md",
  },
  {
    id: "rn-list-performance-item-expensive",
    name: "Move Expensive Work Outside List Items",
    category: "List Performance",
    impact: "CRITICAL" as const,
    description: "Pre-compute expensive data transformations outside list item components so the work isn't repeated on every item render or scroll.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-native-skills/rules/list-performance-item-expensive.md",
  },
  {
    id: "rn-list-performance-item-types",
    name: "Use Item Types for Heterogeneous Lists",
    category: "List Performance",
    impact: "CRITICAL" as const,
    description: "Specify item types in FlashList for lists with mixed item layouts to improve view recycling efficiency and reduce layout work.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-native-skills/rules/list-performance-item-types.md",
  },

  // 2. Animation (HIGH)
  {
    id: "rn-animation-gpu-properties",
    name: "Animate Only Transform and Opacity",
    category: "Animation",
    impact: "MEDIUM-HIGH" as const,
    description: "Restrict animations to transform and opacity properties so they run on the GPU compositor thread without triggering layout or paint.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-native-skills/rules/animation-gpu-properties.md",
  },
  {
    id: "rn-animation-derived-value",
    name: "useDerivedValue for Computed Animations",
    category: "Animation",
    impact: "MEDIUM-HIGH" as const,
    description: "Use Reanimated's useDerivedValue to compute animation values on the UI thread rather than the JS thread for smoother performance.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-native-skills/rules/animation-derived-value.md",
  },
  {
    id: "rn-animation-gesture-detector-press",
    name: "Gesture.Tap Instead of Pressable",
    category: "Animation",
    impact: "MEDIUM-HIGH" as const,
    description: "Use Gesture.Tap from react-native-gesture-handler instead of Pressable when paired with Reanimated to keep gesture handling on the UI thread.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-native-skills/rules/animation-gesture-detector-press.md",
  },

  // 3. Navigation (HIGH)
  {
    id: "rn-navigation-native-navigators",
    name: "Native Stack and Native Tabs",
    category: "Navigation",
    impact: "MEDIUM-HIGH" as const,
    description: "Use native stack navigator and native tab navigator instead of JS-based navigators to get platform-native transitions and better performance on low-end devices.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-native-skills/rules/navigation-native-navigators.md",
  },

  // 4. UI Patterns (HIGH)
  {
    id: "rn-ui-expo-image",
    name: "Use expo-image for All Images",
    category: "UI Patterns",
    impact: "MEDIUM-HIGH" as const,
    description: "Replace the built-in Image component with expo-image for better caching, memory efficiency, and support for modern image formats.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-native-skills/rules/ui-expo-image.md",
  },
  {
    id: "rn-ui-image-gallery",
    name: "Use Galeria for Image Lightboxes",
    category: "UI Patterns",
    impact: "MEDIUM-HIGH" as const,
    description: "Use the Galeria library for image lightbox and gallery experiences instead of custom implementations for better native feel and performance.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-native-skills/rules/ui-image-gallery.md",
  },
  {
    id: "rn-ui-pressable",
    name: "Pressable Over TouchableOpacity",
    category: "UI Patterns",
    impact: "MEDIUM-HIGH" as const,
    description: "Use Pressable instead of TouchableOpacity for press interactions — it offers more flexible style feedback and is the modern recommended API.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-native-skills/rules/ui-pressable.md",
  },
  {
    id: "rn-ui-safe-area-scroll",
    name: "Handle Safe Areas in ScrollViews",
    category: "UI Patterns",
    impact: "MEDIUM-HIGH" as const,
    description: "Apply safe area insets inside ScrollViews using react-native-safe-area-context to avoid content being clipped by notches or home indicators.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-native-skills/rules/ui-safe-area-scroll.md",
  },
  {
    id: "rn-ui-scrollview-content-inset",
    name: "contentInset for Headers",
    category: "UI Patterns",
    impact: "MEDIUM-HIGH" as const,
    description: "Use contentInset on ScrollViews to properly offset content below floating or transparent headers instead of manually adding padding.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-native-skills/rules/ui-scrollview-content-inset.md",
  },
  {
    id: "rn-ui-menus",
    name: "Use Native Context Menus",
    category: "UI Patterns",
    impact: "MEDIUM-HIGH" as const,
    description: "Use native context menu APIs instead of custom JS-rendered menus to get platform-native appearance, animations, and accessibility support.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-native-skills/rules/ui-menus.md",
  },
  {
    id: "rn-ui-native-modals",
    name: "Use Native Modals When Possible",
    category: "UI Patterns",
    impact: "MEDIUM-HIGH" as const,
    description: "Use the platform's native modal presentation instead of JS-rendered overlays to get proper system animations and sheet behavior.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-native-skills/rules/ui-native-modals.md",
  },
  {
    id: "rn-ui-measure-views",
    name: "Use onLayout Instead of measure()",
    category: "UI Patterns",
    impact: "MEDIUM-HIGH" as const,
    description: "Use the onLayout callback to get view dimensions instead of the imperative measure() method to avoid async timing issues.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-native-skills/rules/ui-measure-views.md",
  },
  {
    id: "rn-ui-styling",
    name: "StyleSheet.create or NativeWind",
    category: "UI Patterns",
    impact: "MEDIUM-HIGH" as const,
    description: "Define styles using StyleSheet.create or NativeWind instead of inline objects to enable style caching and improve render performance.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-native-skills/rules/ui-styling.md",
  },

  // 5. State Management (MEDIUM)
  {
    id: "rn-react-state-minimize",
    name: "Minimize State Subscriptions",
    category: "State Management",
    impact: "MEDIUM" as const,
    description: "Subscribe only to the specific state slices a component needs, avoiding broad subscriptions that cause re-renders from unrelated state changes.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-native-skills/rules/react-state-minimize.md",
  },
  {
    id: "rn-react-state-dispatcher",
    name: "Dispatcher Pattern for Callbacks",
    category: "State Management",
    impact: "MEDIUM" as const,
    description: "Use a dispatcher pattern to pass stable callback references into child components instead of recreating functions that break memoization.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-native-skills/rules/react-state-dispatcher.md",
  },
  {
    id: "rn-react-state-fallback",
    name: "Show Fallback on First Render",
    category: "State Management",
    impact: "MEDIUM" as const,
    description: "Return a lightweight fallback on the first render when state is uninitialized to avoid layout thrash and jarring UI shifts.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-native-skills/rules/react-state-fallback.md",
  },
  {
    id: "rn-react-compiler-destructure-functions",
    name: "Destructure Functions for React Compiler",
    category: "State Management",
    impact: "MEDIUM" as const,
    description: "Destructure functions from hooks at the top of render scope instead of dot-accessing them inline so the React Compiler can key caches on stable references.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-native-skills/rules/react-compiler-destructure-functions.md",
  },
  {
    id: "rn-react-compiler-reanimated-shared-values",
    name: "Handle Shared Values with React Compiler",
    category: "State Management",
    impact: "MEDIUM" as const,
    description: "Follow compatibility patterns for Reanimated shared values when using the React Compiler to avoid stale references in animation worklets.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-native-skills/rules/react-compiler-reanimated-shared-values.md",
  },

  // 6. Rendering (MEDIUM)
  {
    id: "rn-rendering-text-in-text-component",
    name: "Wrap Text in Text Components",
    category: "Rendering",
    impact: "MEDIUM" as const,
    description: "Always render text strings inside a <Text> component — placing raw strings directly in <View> causes a runtime crash on native.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-native-skills/rules/rendering-text-in-text-component.md",
  },
  {
    id: "rn-rendering-no-falsy-and",
    name: "Avoid Falsy && for Conditional Rendering",
    category: "Rendering",
    impact: "MEDIUM" as const,
    description: "Use ternary expressions instead of && for conditional rendering to prevent falsy values like 0 or '' from being rendered as visible text on screen.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-native-skills/rules/rendering-no-falsy-and.md",
  },

  // 7. Monorepo (MEDIUM)
  {
    id: "rn-monorepo-native-deps-in-app",
    name: "Keep Native Dependencies in App Package",
    category: "Monorepo",
    impact: "MEDIUM" as const,
    description: "Place native dependencies directly in the app package rather than shared packages to avoid autolinking issues and version conflicts in monorepos.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-native-skills/rules/monorepo-native-deps-in-app.md",
  },
  {
    id: "rn-monorepo-single-dependency-versions",
    name: "Single Dependency Versions Across Packages",
    category: "Monorepo",
    impact: "MEDIUM" as const,
    description: "Enforce a single version of shared dependencies across all monorepo packages to avoid duplicate module bundles and native library conflicts.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-native-skills/rules/monorepo-single-dependency-versions.md",
  },

  // 8. Configuration (LOW)
  {
    id: "rn-fonts-config-plugin",
    name: "Config Plugins for Custom Fonts",
    category: "Configuration",
    impact: "LOW" as const,
    description: "Use Expo config plugins to register custom fonts instead of manually linking them, keeping font setup compatible with Expo's managed workflow.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-native-skills/rules/fonts-config-plugin.md",
  },
  {
    id: "rn-imports-design-system-folder",
    name: "Organize Design System Imports",
    category: "Configuration",
    impact: "LOW" as const,
    description: "Centralize design system components under a dedicated folder with a clean import path to keep UI primitives discoverable and consistently used.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-native-skills/rules/imports-design-system-folder.md",
  },
  {
    id: "rn-js-hoist-intl",
    name: "Hoist Intl Object Creation",
    category: "Configuration",
    impact: "LOW" as const,
    description: "Create Intl formatters (e.g. Intl.NumberFormat, Intl.DateTimeFormat) at module level rather than inside components to avoid expensive re-instantiation on every render.",
    githubUrl: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-native-skills/rules/js-hoist-intl.md",
  },
];
